### PR TITLE
 Added middleware and lower level driver for motor controller

### LINKED ISSUE #5: Add Open Loop Motor Control Firmware
For starters, add some simple Motor Control Firmware in open-loop control mode, to test if everything works fine.

- [ ] Spin Motor1 in Clockwise direction
- [ ] Spin Motor1 in CounterClockwise direction
- [ ] Spin Motor2 in Clockwise direction
- [ ] Spin Motor2 in Counterclockwise direction

### PR DESCRIPTION
**Pull request by aniketSaha1997**

### CODE REVIEW

**Review by sampreets3 — CHANGES_REQUESTED** [review]
I quite like the design of DrvLowMotorMoveForward(selector, speed). This will become much simpler to interface going forward. I suggest to change this back to how it were.

The idea is, that when you're controlling the motors in open-loop, you should be able to address the individual motors and set the speeds of each of them.

**Comment by sampreets3** [comment]
I'd like a couple more changes : 

- Rename the `drv_low` directory to `posit-drivers` _(Separates the device drivers into a space dedicated for this project)_
- Rename the `drv_low(.c/.h)` to `drv8874(.c/.h)` _(We'll be using this space to store all our low-level drivers then)_

**Comment by aniketSaha1997** [comment]
> I quite like the design of DrvLowMotorMoveForward(selector, speed). This will become much simpler to interface going forward. I suggest to change this back to how it were.
> 
> The idea is, that when you're controlling the motors in open-loop, you should be able to address the individual motors and set the speeds of each of them.

This would mean making subsequent calls to control each motor seperately which might induce some delay when the motor operation is required in realtime applications. Though the delay would be very small but still there will be between the instance left motor starts spinning and the right one.

**Comment by sampreets3** [comment]
> This would mean making subsequent calls to control each motor seperately which might induce some delay when the motor operation is required in realtime applications. Though the delay would be very small but still there will be between the instance left motor starts spinning and the right one.

Makes sense, but in that case, how would you address each motor without a selector? Say I want to turn only the left motor at 50% speed. Is that possible with the current API? 

>might induce some delay when the motor operation is required in realtime applications.

Fair point, but honestly I don't think the delay would be as bad. Considering the fact that we're not targeting hard real-time for now, I'd say that's alright.

**Comment by aniketSaha1997** [comment]
> > This would mean making subsequent calls to control each motor seperately which might induce some delay when the motor operation is required in realtime applications. Though the delay would be very small but still there will be between the instance left motor starts spinning and the right one.
> 
> Makes sense, but in that case, how would you address each motor without a selector? Say I want to turn only the left motor at 50% speed. Is that possible with the current API?
> > This api works simply by feeding the CCR register with the passed 'speed' value. And based on the truth table of the PWM mode for forward and reverse motions, one IN is 0 and the other is 1(via pwm). And this happens for both the motors at once so no delay due to individual calls.
> > might induce some delay when the motor operation is required in realtime applications.
> 
> Fair point, but honestly I don't think the delay would be as bad. Considering the fact that we're not targeting hard real-time for now, I'd say that's alright.
>> Ok then i will change the api to have to include the selector.

**Review by sampreets3 — APPROVED** [review]

**Pull request merged**
